# Generated by Django 3.0.5 on 2020-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
